-- ============================================================================
-- ⚠️  WARNING: HAND-WRITTEN MIGRATION — NO LIVE DATABASE WAS AVAILABLE  ⚠️
-- ============================================================================
-- This migration.sql was authored by an AI agent working in a sandbox with
-- NO Postgres connection (no .env, no POSTGRES_PRISMA_URL /
-- POSTGRES_URL_NON_POOLING). It was NOT generated by `prisma migrate dev`
-- against a real database and has NOT been applied or verified anywhere.
--
-- It is a best-effort hand match of this project's existing migration style
-- (see prisma/migrations/20240622023638_auth_maybe/migration.sql etc.) for
-- the schema change: Post.content String -> String?, Post.imageUrl (new,
-- String?).
--
-- BEFORE RELYING ON THIS FILE:
--   1. Run `npx prisma migrate dev` against a real database to regenerate
--      (or confirm) this migration from prisma/schema.prisma.
--   2. Diff the regenerated SQL against this file.
--   3. In CI/production, use `prisma migrate deploy` only after step 1/2.
-- Do not assume this SQL is correct until a real Prisma CLI run confirms it.
-- ============================================================================

-- AlterTable
ALTER TABLE "Post" ADD COLUMN     "imageUrl" TEXT,
ALTER COLUMN "content" DROP NOT NULL;
